# Generated by Django 2.2.7 on 2019-12-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_student_following'),
        ('event', '0005_auto_20191230_0030'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='events',
            field=models.ManyToManyField(related_name='organizations', to='event.Event'),
        ),
        migrations.AddField(
            model_name='organization',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='account.Student'),
        ),
        migrations.AddField(
            model_name='organization',
            name='officers',
            field=models.ManyToManyField(related_name='adminOrg', to='account.Student'),
        ),
    ]
