# Generated by Django 2.2.5 on 2019-10-09 19:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
                ('eventDescription', models.TextField(default='', max_length=650)),
                ('startDate', models.DateTimeField(default=None)),
                ('endDate', models.DateTimeField(default=None)),
                ('eventTags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), default=[], size=None)),
                ('owner', models.CharField(default='', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
