# Generated by Django 2.2.5 on 2019-09-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
