# Generated by Django 2.2.5 on 2019-09-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190928_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.CharField(default='zacharybsy', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
