# Generated by Django 2.2.7 on 2019-12-27 04:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20191226_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventTags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None),
        ),
    ]
