# Generated by Django 2.2.7 on 2019-12-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20191226_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['startDate']},
        ),
    ]
