# Generated by Django 2.2.7 on 2019-12-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='following',
        ),
    ]
